config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  resources :waitlists
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/waitlist.rb
class Waitlist < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/waitlists_controller.rb
class WaitlistsController < ApplicationController
  before_action :set_waitlist, only: %i[ show edit update destroy ]
  before_action :authenticate_admin!, except: %i[ new create ]

  # GET /waitlists or /waitlists.json
  def index
    @waitlists = Waitlist.all
  end

  # GET /waitlists/1 or /waitlists/1.json
  def show
  end

  # GET /waitlists/new
  def new
    @waitlist = Waitlist.new
  end

  # GET /waitlists/1/edit
  def edit
  end

  # POST /waitlists or /waitlists.json
  def create
    @waitlist = Waitlist.new(waitlist_params)

    respond_to do |format|
      if @waitlist.save
        format.html { redirect_to waitlist_url(@waitlist), notice: "Waitlist was successfully created." }
        format.json { render :show, status: :created, location: @waitlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waitlists/1 or /waitlists/1.json
  def update
    respond_to do |format|
      if @waitlist.update(waitlist_params)
        format.html { redirect_to waitlist_url(@waitlist), notice: "Waitlist was successfully updated." }
        format.json { render :show, status: :ok, location: @waitlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @waitlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waitlists/1 or /waitlists/1.json
  def destroy
    @waitlist.destroy

    respond_to do |format|
      format.html { redirect_to waitlists_url, notice: "Waitlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waitlist
      @waitlist = Waitlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def waitlist_params
      params.require(:waitlist).permit(:name, :business_name, :email, :market, :customer_base, :enable_customers, :challenges)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/waitlists_helper.rb
module WaitlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BevApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>

    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
    <%= yield %>
  </body>
</html>

app/views/waitlists/_form.html.erb
<%= form_with(model: waitlist) do |form| %>
  <% if waitlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(waitlist.errors.count, "error") %> prohibited this waitlist from being saved:</h2>

      <ul>
        <% waitlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Name or Business Name", style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label "Business Type (pub, Restaurant, cAfe or Coffee Shop)", style: "display: block" %>
    <%= form.text_field :business_name %>
  </div>

  <div>
    <%= form.label "Email Address", style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label "Do you think there is a market for customers to buy & redeem beverages on an app?", style: "display: block" %>
    <%= form.check_box :market %>
  </div>

  <div>
    <%= form.label "Would you be interested in opening your customer base to people outside of your premises?", style: "display: block" %>
    <%= form.check_box :customer_base %>
  </div>

  <div>
    <%= form.label "Would you register your business on an easy-to-use app to enable customers to purchase beverages for their friends?", style: "display: block" %>
    <%= form.check_box :enable_customers %>
  </div>

  <div>
    <%= form.label "What are the biggest challenges for your business with this?", style: "display: block" %>
    <%= form.text_field :challenges %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/waitlists/_waitlist.html.erb
<div id="<%= dom_id waitlist %>">
  <p>
    <strong>Name:</strong>
    <%= waitlist.name %>
  </p>

  <p>
    <strong>Business name:</strong>
    <%= waitlist.business_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= waitlist.email %>
  </p>

  <p>
    <strong>Market:</strong>
    <%= waitlist.market %>
  </p>

  <p>
    <strong>Customer base:</strong>
    <%= waitlist.customer_base %>
  </p>

  <p>
    <strong>Enable customers:</strong>
    <%= waitlist.enable_customers %>
  </p>

  <p>
    <strong>Challenges:</strong>
    <%= waitlist.challenges %>
  </p>

</div>

app/views/waitlists/edit.html.erb
<h1>Editing waitlist</h1>

<%= render "form", waitlist: @waitlist %>

<br>

<div>
  <%= link_to "Show this waitlist", @waitlist %> |
  <%= link_to "Back to waitlists", waitlists_path %>
</div>

app/views/waitlists/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Waitlists</h1>

<div id="waitlists">
  <% @waitlists.each do |waitlist| %>
    <%= render waitlist %>
    <p>
      <%= link_to "Show this waitlist", waitlist %>
    </p>
  <% end %>
</div>

<%= link_to "New waitlist", new_waitlist_path %>

app/views/waitlists/new.html.erb
<%= render "form", waitlist: @waitlist %>

<br>

<div>
  <%= link_to "Back to waitlists", waitlists_path %>
</div>

app/views/waitlists/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @waitlist %>

<div>
  <%= link_to "Edit this waitlist", edit_waitlist_path(@waitlist) %> |
  <%= link_to "Back to waitlists", waitlists_path %>

  <%= button_to "Destroy this waitlist", @waitlist, method: :delete %>
</div>